server:
  port: 8800
spring:
  elasticsearch:
    ip: 127.0.0.1 #可配置多个，以逗号间隔举例： ip,ip
    port: 9200
    username: xueyujiao
    password: Xue233201!
    connection-timeout: 1
    read-timeout: 30

minio:
  access-key: xueyujiao
  secret-key: Xue233201!
  bucket: leadnews
  endpoint: http://localhost:9000
  read-path: http://localhost:9000
